name = "Pinecone"
uuid = "ee90fdae-f7f0-4648-8b00-9c0307cf46d9"
authors = ["Tim Tully <tim@menlovc.com>"]
version = "1.1.1"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
HTTP = "0.9, 1"
JSON3 = "1"
StructTypes = "1"
julia = "1.1"
